### ISSUE TITLE
@conda-forge-admin, please update version

### ISSUE THREAD

**Issue by klauer** [conda-forge/setuptools_scm-feedstock#67]
### Additional comment:

I'm not sure if I'm allowed to do this (I maintain a bunch of other feedstocks but not this one)
Regardless, v8.0.1 which was just released in this PR (https://github.com/conda-forge/setuptools_scm-feedstock/pull/66) broke Python 3.9 on my feedstocks which use setuptools-scm.
It appears that v8.0.3 (released 4 days ago) fixes this.

Upstream PR: https://github.com/pypa/setuptools_scm/pull/929
Tag: https://github.com/pypa/setuptools_scm/releases/tag/v8.0.3

(And apologies if this is stepping on any toes; hopefully it saves you a step instead)

**Comment by ocefpaf** [comment]
> I'm not sure if I'm allowed to do this

You are :smile: 

> I maintain a bunch of other feedstocks but not this one

You are just one more bot command to add yourself here. Want to do it too? We can use more maintainers ;-p
